
<!--MAIN CONTENT-->
<main class="container">
    <section id="noel">
        <h1>C'est noël, profitez-en !</h1>
        <img src="<?= $wwwUrl ?>img/offre-noel.jpg" alt="" />
        <small>Pour toute commande effectuée avant le 20 décembre</small>
    </section>
    <section id="slider">
        <div class="flexslider">
            <ul class="slides">
                <li><img src="<?= $wwwUrl ?>img/slider/1.jpg" alt="Photo du slider" /></li>
                <li><img src="<?= $wwwUrl ?>img/slider/2.jpg" alt="Photo du slider" /></li>
            </ul>
        </div>
    </section>
    <section id="categorie">
        <h2><span>Choisissez votre thé</span></h2>
        <a href="#">
            <img src="<?= $wwwUrl ?>img/tea/1.jpg" alt="Thé noir" />
            <h3>Thé noir</h3>
        </a>
        <a href="#">
            <img src="<?= $wwwUrl ?>img/tea/2.jpg" alt="Thé vert" />
            <h3>Thé vert</h3>
        </a>
        <a href="#">
            <img src="<?= $wwwUrl ?>img/tea/3.jpg" alt="Oolong" />
            <h3>Oolong</h3>
        </a>
        <a href="#">
            <img src="<?= $wwwUrl ?>img/tea/4.jpg" alt="Thé blanc" />
            <h3>Thé blanc</h3>
        </a>
        <a href="#">
            <img src="<?= $wwwUrl ?>img/tea/5.jpg" alt="Rooibos" />
            <h3>Rooibos</h3>
        </a>
    </section>
    <section id="tea">
        <article id="new">
            <h2><span>Notre nouveauté</span></h2>
            <img src="<?= $wwwUrl ?>img/product/product1.jpg" alt="Thé du Hammam" />
            <h3>Thé du hammam</h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
            <section class="price">
                <p>À partir de <strong>8,50€</strong></p>
            </section>
            <a class="btn" href="#">Voir ce produit</a>
        </article>
        <article id="best">
            <h2><span>Notre best-seller</span></h2>
            <img src="<?= $wwwUrl ?>img/product/product2.jpg" alt="Infustion Herboriste" />
            <h3>Infusion Herboriste</h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
            <section class="price">
                <p>À partir de <strong>7,60€</strong></p>
            </section>
            <a class="btn" href="#">Voir ce produit</a>
        </article>
        <article id="crush">
            <h2><span>Notre coup de coeur</span></h2>
            <img src="<?= $wwwUrl ?>img/product/product3.jpg" alt="Blue of London" />
            <h3>Blue of London</h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
            <section class="price">
                <p>À partir de <strong>9,00€</strong></p>
            </section>
            <a class="btn" href="product.html">Voir ce produit</a>
        </article>
    </section>
</main>



