
<div class="wrapForm">
	<form action="<?= $requestUrl;	?>/inscription" method="POST" />

		<label for="name" >
			Nom:
				<input type="text" name="name" />
		</label>

		<label for="email" >
			Email:
				<input type="text" name="email" />
		</label>

		<label for="pass" >
			Password:
				<input type="text" name="password" />
		</label>
		

		<input type="submit" value="S'inscrire" />
	</form>
</div>