
<div class="wrapForm">
	<form action="<?= $requestUrl;	?>/inscription" method="POST" />
		<aside class="error-message">
		<p></p>
		</aside>
		<label for="name" >
			Nom:
				<input type="text" name="name" data-required data-name="nom"/>
		</label>

		<label for="email" >
			Email:
				<input type="text" name="email" data-required data-name="email"/>
		</label>

		<label for="pass" >
			Password:
				<input type="text" name="password" data-length=8 data-name="mot de passe"/>
		</label>
		

		<input type="submit" value="S'inscrire" />
	</form>
</div>

<script src="<?= $wwwUrl;	?>js/classes/FormValidator.class.js" ></script>
