<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>GitHub</title>

</head>
<body>

    <!-- En-tête commune -->
    <header>
 
    </header>

    <!-- Interface utilisateur -->
    <nav class="user-interface">
       
    </nav>

    <main>
        <!-- Affichage du template lié à la vue -->
        <?php include $template.".phtml"; ?>
    </main>

    <!-- Pied de page commun -->
    <footer>
       
    </footer>

</body>
</html>