<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <!-- CSS Vendor -->
    <link rel="stylesheet" type="text/css" href="css/font-awesome.min.css" />
    <link rel="stylesheet" type="text/css" href="css/flexslider.css" media="screen" />
    <!-- CSS Perso -->
    <link rel="stylesheet" type="text/css" href="css/normalize.css" media="screen" />
    <link rel="stylesheet" type="text/css" href="css/base.css" media="screen" />
    <link rel="stylesheet" type="text/css" href="css/style.css" media="screen" />
    <!-- Perso JS -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.6.2/jquery.min.js"></script>
    <script src="js/jquery.flexslider-min.js"></script>
    <script type="text/javascript">
        $(window).load(function() {
            $('.flexslider').flexslider({
                directionNav: false
            });
        });
    </script>
    <title>GitHub</title>

</head>
<body>

    <!-- En-tête commune -->
    <header>
 
    </header>

    <!-- Interface utilisateur -->
    <nav class="user-interface">
       
    </nav>

    <main>
        <!-- Affichage du template lié à la vue -->
        <?php include $template.".phtml"; ?>
    </main>

    <!-- Pied de page commun -->
    <footer>
       
    </footer>

</body>
</html>