<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <!-- CSS Vendor -->
    <link rel="stylesheet" type="text/css" href="<?= $wwwUrl;    ?>css/font-awesome.min.css" />
    <link rel="stylesheet" type="text/css" href="<?= $wwwUrl;    ?>css/flexslider.css" media="screen" />
    <!-- CSS Perso -->
    <link rel="stylesheet" type="text/css" href="<?= $wwwUrl;    ?>css/normalize.css" media="screen" />
    <link rel="stylesheet" type="text/css" href="<?= $wwwUrl;    ?>css/base.css" media="screen" />
    <link rel="stylesheet" type="text/css" href="<?= $wwwUrl;    ?>css/style.css" media="screen" />
    <!-- Perso JS -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.6.2/jquery.min.js"></script>
    <script src="<?= $wwwUrl;    ?>js/jquery.flexslider-min.js"></script>
    <script type="text/javascript">
        $(window).load(function() {
            $('.flexslider').flexslider({
                directionNav: false
            });
        });
    </script>
    <title>GitHub</title>

</head>
<body>

    <!-- En-tête commune -->
    <header>
        <img class="ribbon" src="<?= $wwwUrl ?>img/ribbon.svg" alt="élu meilleur thé en 2016" />
        <section id="topbar">Livraison offerte à partir de 65€ d'achat !</section>
        <div class="container">
            <section id="logo">
                <a href="index.html">
                    <img src="<?= $wwwUrl ?>/img/logo.png" alt="Logo de Cup of Tea" />
                </a>
                <section id="cart">
                    <span>Mon panier</span>
                    <strong>42,00€</strong>
                </section>
            </section>
            <nav>
                <a href="<?= $requestUrl ?>/listing-product">Thés</a>

                <a href="<?= $requestUrl ?>/product">Produit</a>

                <a href="<?= $requestUrl ?>/about">About Us</a>

            </nav>
        </div>
    </header>
    <!-- Interface utilisateur -->
    <nav class="user-interface">


    </nav>

    <main>
        <!-- Affichage du template lié à la vue -->
        <?php include $template.".phtml"; ?>
    </main>

    <!-- Pied de page commun -->

    <footer>
        <section id="info">
            <article>
                <i class="fa fa-lock"></i>
                <small>Paiement sécurisé</small>
            </article>
            <article>
                <i class="fa fa-truck"></i>
                <small>Ma livraison offerte</small>
            </article>
            <article>
                <i class="fa fa-money"></i>
                <small>Carte de fidélité</small>
            </article>
            <article>
                <i class="fa fa-phone"></i>
                <small>Service client</small>
            </article>
            <article>
                <i class="fa fa-check-circle"></i>
                <small>Garantie qualité</small>
            </article>
        </section>
        <section id="bottombar">
            <article>
                <h2>Cup of Tea</h2>
                <ul>
                    <li>Notre histoire</li>
                    <li>Nos boutiques</li>
                    <li>Le Thé de A à Z</li>
                    <li>Espace clients professionnels</li>
                    <li>Recrutement</li>
                    <li>Contactez-nous !</li>
                    <li>L'École du Thé</li>
                </ul>
            </article>
            <article>
                <h2>Commandez en ligne</h2>
                <ul>
                    <li>Première visite</li>
                    <li>Aide - FAQ</li>
                    <li>Service client</li>
                    <li>Suivre ma commande</li>
                    <li>Conditions générales de vente</li>
                    <li>Informations légales</li>
                </ul>
            </article>
            <article>
                <h2>Suivez-nous !</h2>
                <ul>
                    <li>Notre histoire</li>
                    <li>Nos boutiques</li>
                    <li>Le Thé de A à Z</li>
                    <li>Espace clients professionnels</li>
                </ul>
            </article>
        </section>
    </footer>

</body>
</html>
