
<main class="container">
			<section class="tea">
				<img src="<?= $wwwUrl;    ?>img/tea/1.jpg" alt="Tasse de thé noir" />
				<h2><span>Thé noir</span></h2>
				<p class="clear">Le thé noir, que les chinois appellent thé rouge en référence à la couleur cuivrée de son infusion, est un thé complètement oxydé. La fabrication du thé noir se fait en cinq étapes : le flétrissage, le roulage, l'oxydation, la torréfaction et le triage. Cette dernière opération permet de différencier les différents grades.</p>
				<section class="listing-product">
					<article>
						<h3>Blue of london</h3>
						<img src="<?= $wwwUrl;    ?>img/product/product3_big.jpg" alt="Photo du thé" />
						<section class="price">
							<p>À partir de <strong>7,50€</strong></p>
						</section>
						<a class="btn" href="product.html">Voir ce produit</a>
					</article>
					<article>
						<h3>Thé des lords</h3>
						<img src="<?= $wwwUrl;    ?>img/product/product6_big.jpg" alt="Photo du thé" />
						<section class="price">
							<p>À partir de <strong>8,20€</strong></p>
						</section>
						<a class="btn" href="#">Voir ce produit</a>
					</article>
					<article>
						<h3>Thé des vahinés</h3>
						<img src="<?= $wwwUrl;    ?>img/product/product7_big.jpg" alt="Photo du thé" />
						<section class="price">
							<p>À partir de <strong>9,40€</strong></p>
						</section>
						<a class="btn" href="#">Voir ce produit</a>
					</article>
				</section>
			</section>
			<section class="tea">
				<img src="<?= $wwwUrl;    ?>img/tea/2.jpg" alt="Tasse de thé vert" />
				<h2><span>Thé vert</span></h2>
				<p class="clear">Réputé pour ses nombreuses vertus grâce à sa richesse en antioxydants, le thé vert désaltère, tonifie, apaise, fortifie, et procure une incontestable sensation de bien-être. Délicat et peu amer, il est apprécié à tout moment de la journée et propose une palette d'arômes très variés : végétal, minéral, floral, fruité.</p>
				<section class="listing-product">
					<article>
						<h3>Thé du hammam</h3>
						<img src="<?= $wwwUrl;    ?>img/product/product1_big.jpg" alt="Photo du thé" />
						<section class="price">
							<p>À partir de <strong>8,40€</strong></p>
						</section>
						<a class="btn" href="#">Voir ce produit</a>
					</article>
					<article>
						<h3>Vive le thé !</h3>
						<img src="<?= $wwwUrl;    ?>img/product/product4_big.jpg" alt="Photo du thé" />
						<section class="price">
							<p>À partir de <strong>6,80€</strong></p>
						</section>
						<a class="btn" href="#">Voir ce produit</a>
					</article>
					<article>
						<h3>Thé des alizés</h3>
						<img src="<?= $wwwUrl;    ?>img/product/product5_big.jpg" alt="Photo du thé" />
						<section class="price">
							<p>À partir de <strong>9,30€</strong></p>
						</section>
						<a class="btn" href="#">Voir ce produit</a>
					</article>
				</section>
			</section>
			<section class="tea">
				<img src="<?= $wwwUrl;    ?>img/tea/3.jpg" alt="Tasse de Oolong" />
				<h2><span>Oolong</span></h2>
				<p class="clear">Les Oolong, que les chinois appellent thés bleu-vert en référence à la couleur de leurs feuilles infusées, sont des thés semi-oxydés : leur oxydation n'a pas été menée à son terme. Spécialités de Chine et de Taïwan, il en existe une grande variété, en fonction de la région de culture, de l'espèce du théier ou encore du processus de fabrication.</p>
				<section class="listing-product">
					<article>
						<h3>Vive les fetes</h3>
						<img src="<?= $wwwUrl;    ?>img/product/product8_big.jpg" alt="Photo du thé" />
						<section class="price">
							<p>À partir de <strong>11,10€</strong></p>
						</section>
						<a class="btn" href="#">Voir ce produit</a>
					</article>
					<article>
						<h3>Fleur d'oranger Oolong</h3>
						<img src="<?= $wwwUrl;    ?>img/product/product9_big.jpg" alt="Photo du thé" />
						<section class="price">
							<p>À partir de <strong>10,90€</strong></p>
						</section>
						<a class="btn" href="#">Voir ce produit</a>
					</article>
					<article>
						<h3>Oolong 7 agrumes</h3>
						<img src="<?= $wwwUrl;    ?>img/product/product10_big.jpg" alt="Photo du thé" />
						<section class="price">
							<p>À partir de <strong>13,20€</strong></p>
						</section>
						<a class="btn" href="#">Voir ce produit</a>
					</article>
				</section>
			</section>
			<section class="tea">
				<img src="<?= $wwwUrl;    ?>img/tea/4.jpg" alt="Tasse de Thé blanc" />
				<h2><span>Thé blanc</span></h2>
				<p class="clear">Le thé blanc est une spécialité de la province chinoise du Fujian. De toutes les familles de thé, c'est celle dont la feuille est la moins transformée par rapport à son état naturel. Non oxydé, le thé blanc ne subit que deux opérations : un flétrissage et une dessiccation. Il existe deux grands types de thés blancs : les Aiguilles d'Argent et les Bai Mu Dan.</p>
				<section class="listing-product">
					<article>
						<h3>Thé des songes blanc</h3>
						<img src="<?= $wwwUrl;    ?>img/product/product11_big.jpg" alt="Photo du thé" />
						<section class="price">
							<p>À partir de <strong>12,00€</strong></p>
						</section>
						<a class="btn" href="#">Voir ce produit</a>
					</article>
					<article>
						<h3>Bai mu dan</h3>
						<img src="<?= $wwwUrl;    ?>img/product/product12_big.jpg" alt="Photo du thé" />
						<section class="price">
							<p>À partir de <strong>9,50€</strong></p>
						</section>
						<a class="btn" href="#">Voir ce produit</a>
					</article>
					<article>
						<h3>Auguilles d'argent</h3>
						<img src="<?= $wwwUrl;    ?>img/product/product13_big.jpg" alt="Photo du thé" />
						<section class="price">
							<p>À partir de <strong>47,20€</strong></p>
						</section>
						<a class="btn" href="#">Voir ce produit</a>
					</article>
				</section>
			</section>
			<section class="tea">
				<img src="<?= $wwwUrl;    ?>img/tea/5.jpg" alt="Tasse de Rooibos" />
				<h2><span>Rooibos</span></h2>
				<p class="clear">Le Rooibos (appelé thé rouge bien qu'il ne s'agisse pas de thé) est une plante poussant uniquement en Afrique du Sud et qui ne contient pas du tout de théine. Son infusion donne une boisson très agréable, ronde et légèrement sucrée. Riche en antioxydants, faible en tanins et dénué de théine, le Rooibos peut être dégusté en journée comme en soirée.</p>
				<section class="listing-product">
					<article>
						<h3>Rooibos à la verveine</h3>
						<img src="<?= $wwwUrl;    ?>img/product/product14_big.jpg" alt="Photo du thé" />
						<section class="price">
							<p>À partir de <strong>7,00€</strong></p>
						</section>
						<a class="btn" href="#">Voir ce produit</a>
					</article>
					<article>
						<h3>Spicy Passion</h3>
						<img src="<?= $wwwUrl;    ?>img/product/product15_big.jpg" alt="Photo du thé" />
						<section class="price">
							<p>À partir de <strong>9,00€</strong></p>
						</section>
						<a class="btn" href="#">Voir ce produit</a>
					</article>
					<article>
						<h3>Rooibos des amants</h3>
						<img src="<?= $wwwUrl;    ?>img/product/product16_big.jpg" alt="Photo du thé" />
						<section class="price">
							<p>À partir de <strong>8,20€</strong></p>
						</section>
						<a class="btn" href="#">Voir ce produit</a>
					</article>
				</section>
			</section>
		</main>