
<main class="container">

			<?php foreach($categories as $category):	?>
				<section class="tea">
				<img src="<?= $wwwUrl;    ?>img/tea/<?= $category['categoryPhoto'];	?>" alt="<?= $category['categoryName'];	?>" />
				<h2><span><?= $category['categoryName'];	?></span></h2>
				<p class="clear"><?= $category['categoryDescription'];	?></p>
				<section class="listing-product">
				<?php foreach ($teas as $index=>$tea) :	?>
					<?php if($tea['category']==$category['categoryId']):	?>
						<article>
							
								<h3><?= $tea['name'];	?></h3>
								<img src="<?= $wwwUrl;    ?>img/product/<?= $tea['photo'];	?>" alt="Photo du thé" />
								<section class="price">
									<p>À partir de <strong><?= number_format($tea['salePrice'],2) ;	?> €</strong></p>
								</section>
								<a class="btn" href="product.html">Voir ce produit</a>
							</article>
						
					<?php endif;	?>
				<?php endforeach;	?>
				</section>
				</section>
			<?php endforeach;	?>
			
		</main>
