<main class="container">
    <section id="product">
        <section id="product-detail">
            <div id="product-name">
                <h3><?= $tea['name'];   ?></h3>
                <h4><?= $tea['summary'];    ?></h4>
                <p>Ref : <?= $tea['ref'];   ?></p>
            </div>
            <div id="rating">
                <i class="gold fa fa-star" aria-hidden="true"></i>
                <i class="gold fa fa-star" aria-hidden="true"></i>
                <i class="gold fa fa-star" aria-hidden="true"></i>
                <i class="gold fa fa-star" aria-hidden="true"></i>
                <i class="fa fa-star" aria-hidden="true"></i>
                <a href="#">Voir les 56 avis clients</a>
            </div>
        </section>
        <section id="product-quantity">
            <img src="<?= $wwwUrl;    ?>img/product/<?= $tea['photo']; ?>" alt="" />
            <div class="price">
                <select name="quantity">
                    <option>Pochette de 100gr</option>
                    <option>Pochette de 500gr</option>
                    <option>Pochette de 1kg</option>
                </select>
                <h4>9,00€</h4>
                <a class="btn" href="#">Ajouter au panier</a>
                <a id="wishlist" href="#">Ajouter à ma liste d'envie</a>
            </div>
        </section>
        <section id="product-description">
            <p><?= $tea['description']; ?></p>
            <p><strong>Profitez d'une remise de 5% sur la pochette de 500g (prix déjà remisé).</strong></p>
            <p><strong>Profitez d'une remise de 10% sur le lot de 2 pochettes de 500g (prix déjà remisé).</strong></p>
        </section>
    </section>
</main>
